appsignal/appsignal-elixir-phoenix

- lib/appsignal_phoenix/view.ex
This patch clears warnings with apps that have an overridden `render/2` function.
> Move render/2 definition to Appsignal.Phoenix.View.__before_compile__/1 

- lib/appsignal_phoenix/view.ex
- test/appsignal_phoenix/view_test.exs
Closes https://github.com/appsignal/appsignal-elixir-phoenix/issues/5.
Closes https://github.com/appsignal/appsignal-elixir/issues/588.
Phoenix.View.render/2 can be called with a module name as the first argument,
causing the call to be redirected to Phoenix.View.render/3. This patch makes
sure we let the call go through unchanged, which prevents double
instrumentation from happening and fixes the reported dialyzer issues.
This is planned to be released as 2.0.1
> Add clause for non-binary template names in AppsignalPhoenix.View

- lib/appsignal_phoenix/application.ex
- lib/appsignal_phoenix/channel.ex
- lib/appsignal_phoenix/view.ex
- mix.exs
Since the `Span.set_attribute/3` function takes and returns `Span`s and `nil`s,
we don't care about the return value here, as either case is accounted for.
The Application starts the EventHandler, which logs errors itself. Since we
don't do anyhthing else there, we don't need to catch the return.
Part of closing #5.
> Explicitly ignore returns from Span functions

- lib/appsignal_phoenix/live_view.ex
- test/appsignal_phoenix/live_view_test.exs
Since the LiveView instrumentation used the channels instrumentation, the namespaces were set to “channel” instead of “live_view”, as in the documentation. This patch duplicates the channel instrumentation to update the namespace.
To test this, call an instrumented LiveView action in a Phoenix app while running this version of the library. Your dependency should look like this:
```
{:appsignal_phoenix, github: "appsignal/appsignal-elixir-phoenix", branch: "live_view_namespace"}
```
> Use “live_view” namespace for LiveView samples

- lib/appsignal_phoenix/live_view.ex
This PR Adds live_view_action/5. Its appears a perfect fit for https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#c:handle_params/3
(Not sure why it was excluded from you API in the first place? I'm assuming https://docs.appsignal.com/guides/filter-data/filter-parameters.html#elixir-appsignal-parameter-filtering still works?)
> Exposes live_view_action/5 to help instrument handle_params

- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/view.ex
- mix.exs
Part of https://github.com/appsignal/appsignal-elixir/issues/634, this patch is the -phoenix equivalent of https://github.com/appsignal/appsignal-elixir-plug/pull/11 and uses `Appsignal.Logger.debug/1` instead of `Logger.debug/1` to only send log lines to Elixir’s `Logger` when AppSignal’s `:debug` configuration is set to `true`.
> Use Appsignal.Logger in Appsignal.Phoenix.View and .EventHandler

- .changesets/phoenix-liveview-socket-root_view
- lib/appsignal_phoenix/metadata.ex
- test/appsignal_phoenix/live_view_test.exs
In
phoenixframework/phoenix_live_view@8bb6f44,
the root_view key was made private. This patch makes sure the LiveView
instrumentation handles both cases.
Closes #15.
> Take root_view from private in LiveView handler 

- CHANGELOG.md
- mono.yml
Use our own tooling for development in the Elixir integration repos.
https://github.com/appsignal/mono/
Follow the instructions on the mono README to install it locally.
Mono repo support for Elixir isn't 100% feature complete yet so we're
first adding it to every repo separately. Right now we'll use it for
changesets, changelogs and publishing the package.
I didn't add mono to the Semaphore CI test setup as it doesn't really
add anything there at this point. I also didn't add it to the main
Elixir package's CI yet either.
[skip review]
> Add mono to project

- .changesets/only-create-template-spans-when-a-root-span-exists.md
- lib/appsignal_phoenix/view.ex
- test/appsignal_phoenix/view_test.exs
Let's take this `handle_event/3` as an example, which is instrumented
through our `Appsignal.Phoenix.LiveView.instrument/4` helper:
``` elixir
@impl true
def handle_event("suggest", %{"q" => query}, socket) do
instrument(__MODULE__, "suggest", socket, fn ->
{:noreply, assign(socket, results: search(query), query: query)}
end)
end
```
This handler updates the page by changing the assigns by updating the
socket.  When that happens, LiveView automatically rerenders the
template to show the new data, which AppSignal tracks through the
`Appsignal.View` module automatically.
Because this function is wrapped in an `instrument/4` call, a span
gets created when it's called.  There's no parent span here, so it
creates a "root span", which tells the integration to set the
namespace and other …
> Only create template spans when a root span exists

- .changesets/return-templates-when-appsignals-view-instrumentation-is-disabled.md
- lib/appsignal_phoenix/view.ex
- test/appsignal_phoenix/view_test.exs
A regression in 2.0.8 caused view renders that didn't have a root span
to fail to return the rendered template. This patch makes sure the
template is rendered even if AppSignal's template instrumentation is
disabled.
Closes https://github.com/appsignal/appsignal-elixir-phoenix/issues/20.
> Ensure templates get rendered without root spans

- .changesets/resolve-duplicate-view-clause-warnings-from-appsignal-view.md
- lib/appsignal_phoenix/view.ex
- test/appsignal_phoenix/view_test.exs
The test for the `is_binary/1` check broke in a previous commit,
allowing this issue to go unnoticed. This patch restores the test to
actually call the `render/2` function with a non-binary first
argument, and resolves the duplicate clause warning appearing in apps
using `Appsignal.View`.
This patch resolves the warnings reported in https://github.com/appsignal/appsignal-elixir-phoenix/issues/20#issuecomment-881396763.
> Restore is_binary/1 check in View.render/2

- .semaphore/semaphore.yml
Using master Elixir version for linter jobs isn't required and is prone
to breaking CI.
Co-authored-by: Jeff Kreeftmeijer <jeffkreeftmeijer@gmail.com>
> Update elixir version for CI linters

- .changesets/allow-using-phoenix_html-3-0-0-and-up.md
- mix.exs
This PR resolves the dependency conflict when using `phoenix_html`
> Update phoenix html dependency

- .changesets/remove-unneeded-telemetry-dependency.md
- mix.exs
Telemetry dependency is not needed for this library as it is already a dependency of appsignal-elixir, which this library depends on through appsignal-plug.
Has to be deployed before https://github.com/appsignal/appsignal-elixir/pull/664 to avoid conflicts.
> Remove telemetry dependency

- mix.exs
Mime is depended on by plug in all environments. CI
breaks on Elixir 1.9.4 if it picks mime 2.0.x. This patch explicitly
locks to mime ~> 1.0 on Elixir versions before 1.10.
> Resolve mime dependency issue for Elixir 1.9

- .semaphore/semaphore.yml
- bin/setup
- config/config.exs
- mix.exs
- test/appsignal_phoenix/event_handler_test.exs
- test/appsignal_phoenix/live_view_test.exs
- test/appsignal_phoenix_test.exs
- test/support/phoenix_web.ex
CI was running with older versions of OTP and Elixir. Updated it to work
as the Elixir library.
We are adding a compilation step on CI with warnings as errors. We have
to get rid of them to make the build pass.
> Update ci builds versions

- .semaphore/semaphore.yml
- bin/setup
The Semaphore-provided utilities, such as `sem-version`, are provided as shell functions. To use them from a script, the script must be sourced, not invoked. As such, before this commit, calls to `sem-version` within the `bin/setup` script were failing, and all the test runs were using the versions of Elixir and Erlang provided by Semaphore by default.
This commit also renames the Elixir `master` version to `main`, which was not failing before for the same reason.
This commit reproduces the changes in [appsignal-elixir#718][pr] for the Phoenix repository, making it so that the intended Erlang and Elixir versions are used, by selecting the Erlang version before the Elixir one, compiling the desired Elixir version against the selected Erlang version, caching the compiled …
> Fix Erlang/OTP and Elixir version in CI

- lib/appsignal_phoenix/channel.ex
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/live_view.ex
- lib/appsignal_phoenix/template.ex
- lib/appsignal_phoenix/view.ex
- mix.exs
to avoid warnings on Elixir 1.14+
> Use Appsignal.Utils.compile_env in Appsignal.Phoenix

- .changesets/add-event-names-to-liveview-events.md
- lib/appsignal_phoenix/live_view.ex
- mix.exs
- test/appsignal_phoenix/live_view_test.exs
As requested in https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/conversation/16410700131606.
In handle_event_start/3, use the event name to add as the value for the
"event" attribute if it's set.
Because the changes in https://github.com/appsignal/appsignal-elixir-phoenix/commit/2eb6ec82f0edf3038815f9cfee59f0e030fc7c7c could
send nil values to Span.set_attribute/3 function, appsignal 2.2.15 or
above is required for that patch to work.
> Add event names to LiveView instrumentation

- .changesets/handle-live_component-events-in-liveview-integration.md
- lib/appsignal_phoenix/live_view.ex
- mix.exs
- test/appsignal_phoenix/live_view_test.exs
This pull request is a copy of @aj-foster’s work in #47, with a fix to make the tests pass an a patch to remove the separate clause for the live_component type. The latter requires us to depend on :appsignal 2.2.16 or above, as that version includes https://github.com/appsignal/appsignal-elixir/pull/788.
> Add live_component handler to the LiveView integration

- .semaphore/semaphore.yml
- .semaphore/semaphore.yml.erb
- .semaphore/versions.rb
- mix.exs
- script/generate_ci_matrix
- script/validate_ci_matrix
Instead of periodically updating the CI matrix file manually, this patch
adds a script to download the versions.rb file from the main
appsignal-elixir repository, then generate a CI matrix file from that.
That way, this repository's CI matrix always matches the main one,
without any work having to be done to keep them in sync.
This also includes a fix to make sure older versions of :telemetry and
:phoenix_live_view are used on the still-supported OTP 20, which is 
EOL but supported until :appsignal_elixir 3.0 (as per 
https://github.com/appsignal/integration-guide/blob/7cf3b14f89c6cf8d84048ae54a5e739974410b02/maintain/version-support.md#programming-languages)
> Update Elixir and OTP versions in CI matrix

- .changesets/fix-appsignal-logger-error-on-appsignal-for-elixir-1-4-0.md
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/view.ex
- mix.exs
Appsignal.Logger was renamed to Appsignal.IntegrationLogger in :appsignal 2.4.0. This patch switches to using
Appsignal.IntegrationLogger and depends on :appsignal 2.4.0 or above.
> Use renamed Appsignal.IntegrationLogger

- .changesets/add-template-instrumentation-for-phoenix-1-7.md
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/view.ex
- test/appsignal_phoenix/event_handler_test.exs
Instead of using Appsignal.View, Appsignal.EventHandler subscribes to Phoenix 1.7's new template telemetry to gain template rendering insights.
This works on Phoenix applications running on Phoenix edge (https://github.com/phoenixframework/phoenix/commit/f095d1f82cdf18ffc69226fd59ce36a7fc2ffb44 or newer), meaning you won’t have to use `Appsignal.Phoenix.View` to get templates instrumented on the upcoming AppSignal for Phoenix 2.1.0.
> Support Phoenix 1.7's template telemetry

- .changesets/fix-metadata-issue-for-template-telemetry.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
Instead of :type, the key for the template type in the telemetry metadata is now :format.
> Use format instead of type metadata key

- .changesets/fix-exception-handling-for-unwrapped-phoenix-errors.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
If a Plug.Conn.WrapperError is raised, the wrapped stack trace is included in the :stack key. If the raised exception is not wrapped (which happens when it occurs outside of an action, like when failing to mount a live view), the key is :stacktrace.
Closes #62.
> Use :stacktrace for Phoenix telemetry exceptions

- .changesets/fix-logger-deprecation-warnings-on-elixir-1-15.md
- .semaphore/semaphore.yml
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/view.ex
- mix.exs
Update the minimal version of the appsignal dependency to 2.7.4, which is the version that introduces the backwards compatible logging functions in `Appsignal.Utils`. Then, use `Appsignal.Utils.warning/1` in `Appsignal.Phoenix.View` and `Appsignal.Phoenix.EventHandler` to support Elixir 1.10 through 1.15.
Closes #69.
>  Use Appsignal.Utils.warning/1 instead of Logger.warn/1

- .changesets/fix-sample-data-being-overriden-by-phoenix-data.md
- lib/appsignal_phoenix/channel.ex
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/live_view.ex
- mix.exs
- test/appsignal_phoenix/channel_test.exs
- test/appsignal_phoenix/event_handler_test.exs
- test/appsignal_phoenix/live_view_test.exs
Part of https://github.com/appsignal/appsignal-elixir/issues/862.
Before merging this, the version bounds for the `appsignal` and `appsignal-plug` dependencies need to be updated to a version where `set_sample_data_if_nil` is implemented. This requires a release that contains the changes in https://github.com/appsignal/appsignal-elixir/pull/866 and https://github.com/appsignal/appsignal-elixir-plug/pull/37.
The tests are not passing on CI because they are ran against the latest release of the Elixir and Plug integrations, which do not have the `set_sample_data_if_nil` function. They should pass after updating the version bounds as described above.
---
When closing spans, use `set_sample_data_if_nil` instead of `set_sample_data` as to not override custom instrumentation set by the user …
> Use `set_sample_data_if_nil` on span close

- mix.exs
Newer versions of Dialyxir use the
[Kernel.then/2](https://hexdocs.pm/elixir/Kernel.html#then/2) syntax introduced in Elixir 1.12.
Lock the package to 1.3, so we can run it on older versions while we still support them.
Related PR in appsignal-elixir repo:
https://github.com/appsignal/appsignal-elixir/pull/882
See also https://github.com/appsignal/appsignal-elixir/issues/881 for dropping those older versions.
[skip review]
> Lock Dialyxir to 1.3 for older Elixir versions

- mix.exs
It fails to build the `parse_trans` package on OTP < 21, because Hackney bumped its version lock between package version 1.18.1 and 1.18.2. The newer `parse_trans` version requires OTP > 21.
[skip review]
> Fix build by locking Hackney on OTP < 21

- mix.exs
I am not sure where Phoenix.HTML gets used, but seems like its only a dependency to ensure the test still works. 
Updating this allows us to upgrade phoenix_html to 4.0 in phoenix apps using this package.
> Allow phoenix_html 4.0 as a dependency

- .semaphore/semaphore.yml
- .semaphore/semaphore.yml.erb
Ubuntu 18 is in a "brownout phase" and won't run any builds anymore at certain times.
[skip review]
> Update build machine for CI

- .changesets/set-action-name-for-phoenix-actionclauseerror-errors.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
When a Phoenix.ActionClauseError is detected, it will not be able to set the controller and action name as the span (action) name. The connection doesn't have the controller action on its object because there's a function signature mismatch.
The controller action it expects to find can be fetched from the error object. That's what this change does specifically for the Phoenix.ActionClauseError.
- [Related support thread](https://app.intercom.com/a/inbox/yzor8gyw/inbox/shared/unassigned/conversation/16410700311290?view=List)
- [Related internal conversation](https://appsignal.slack.com/archives/CNPP953E2/p1713966958577269)
> Determine action name from ActionClauseErrors

- .changesets/handle-live-view-render-messages.md
- lib/appsignal_phoenix/live_view.ex
- test/appsignal_phoenix/live_view_test.exs
Aside from :mount, :handle_params, and :handle_event, attach to
:render in the LiveView integration.
With this patch, the LiveView integration hooks into all LiveView
telemetry
events (https://hexdocs.pm/phoenix_live_view/telemetry.html).
Fixes https://github.com/appsignal/feature-requests/issues/325
> Attach to [:phoenix, :live_view, :render]

- .changesets/allow-custom-action-names.md
- lib/appsignal_phoenix/event_handler.ex
- mix.exs
- test/appsignal_phoenix/event_handler_test.exs
Set the Phoenix action name using `Span.set_name_if_nil` so we don't overwrite any custom set action names, or those set by other integrations, like our Absinthe one in https://github.com/appsignal/appsignal-elixir/pull/945
> Allow custom action names to be set

- .changesets/add-endpoint-events-to-phoenix-request-traces.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
Previously, the EventHandler ignored endpoint events, mostly because of difficulty determining the root span, as the endpoint and router_dispatch spans close in reverse order. Because of the addition of the root_span functions, this can now be solved, as span data can be set on the root span directly.
This patch moves the span data to the phoenix_endpoint_stop function, which also causes spans to start earlier in the request. That, in turn, means that plugs can be instrumented without changes once again.
Closes #83.
> Handle :phoenix, :endpoint events in EventHandler

- lib/appsignal_phoenix/channel.ex
- lib/appsignal_phoenix/event_handler.ex
- lib/appsignal_phoenix/live_view.ex
- lib/appsignal_phoenix/template.ex
- lib/appsignal_phoenix/view.ex
Appsignal.Utils exposes warning/1 and compile_env/1 functions, which are wrappers to allow for using older Elixir versions. Because we're dropping any Elixir version under 1.11, these are no longer needed.
> Don't use Appsignal.Utils for logging & compiling

- mix.exs
Over the years, we've added version exceptions to the Appsignal for Phoenix dependencies in order for them to run on older versions of OTP and Elixir. Now, since dropping OTP 23 and lower and Elixir 1.10 and lower from CI, some of these can be safely removed.
> Drop OTP <24 & Elixir <1.11 dep version exceptions

- .changesets/add-liveview-1-x-to-allowed-versions-in-dependencies.md
- mix.exs
After verifying that the live view support works on the most recent release candidate, add ~> 1.0 to the version range for the live view dependency.
Closes #91.
> Allow using LiveView 1.0 and up

- .changesets/set-request-metadata-in-router_dispatch-events.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
Since https://github.com/appsignal/appsignal-elixir-phoenix/pull/90, which was released as 2.4.0, we've started supporting Phoenix's /endpoint/ events, which put us a bit higher in the stack, allowing us to get data from pipeline plugs, for example. It also moved setting root span metadata from an event named `[:phoenix, :router_dispatch, :stop]` to the newly added `[:phoenix, :endpoint, :stop]`.
We've learned since that some applications don't publish the endpoint events. We're still figuring out in which situations that happens, but we know that the integration works even if we don't have an endpoint event, as it will automatically fall back to using the router dispatch event as the root span. However, since we set the request metadata on the endpoint event (which doesn't fire for some …
> Set metadata from :router_dispatch stop events

- .changesets/record-request-information-as-metadata.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
Aside from just adding request information to the environment field, add it to the metadata as well to allow for use in filtering.
Fixes https://github.com/appsignal/support/issues/333.
> Record request information as metadata

- .changesets/set-render-metadata-as-tags-on-render-error.md
- lib/appsignal_phoenix/event_handler.ex
- test/appsignal_phoenix/event_handler_test.exs
Intercom conversation: https://app.intercom.com/a/inbox/yzor8gyw/inbox/admin/5246522/conversation/16410700366093?view=List
When an error happens during rendering, the backtrace of it is limited to the Elixir process that is spawned for the rendering task, lacking any context from the customer's own code. To ameliorate this issue, add the rendering metadata as tags to the root span, providing some additional context in the resulting error sample.
> Set render metadata as tags

- .changesets/handle-live-component-update-events.md
- lib/appsignal_phoenix/live_view.ex
- test/appsignal_phoenix/live_view_test.exs
Much like the events already handled, the live_component update event, which is triggered whenever live components are updated.
Closes #102
> Add live_component update event handling

- .github/workflows/ci.yml
For GitHub Actions, we need to specify the PR event to run it for PRs from outside contributors.
[skip review]
> Run CI workflow for Pull Requests

- .changesets/update-update-appsignal_plug-dependency-requirement.md
- lib/appsignal_phoenix/channel.ex
- lib/appsignal_phoenix/live_view.ex
- mix.exs
Update the dependency so all new packages use the fix linked below that ensures that spans created by our plug package aren't trying to close twice.
See also PR https://github.com/appsignal/appsignal-elixir-plug/pull/51 and PR https://github.com/appsignal/appsignal-elixir/pull/979
The tests failed because the spans were closed twice. Remove the close span call in this package and rely on the `Appsignal.instrument` helper's behavior to close a span if an error occurred in the instrumented function.
See also PR https://github.com/appsignal/appsignal-elixir-plug/pull/51 and PR https://github.com/appsignal/appsignal-elixir/pull/979
> Remove double close calls on spans

- mix.exs
Update the minimal requirement so that it matches the appsignal_plug package's requirement. It just makes it consistent.
[skip review]
> Bump AppSignal package to version 2.15.0

- .changesets/remove-hackney-dependency--not-used.md
- mix.exs
Remove the dependency so we don't include a dependency that's no longer used by the main AppSignal package.
[skip review]
> Remove unused hackney dependency

- config/config.exs
- mix.exs
Use the phoenix default json lib (Jason for now).
[skip review]
[skip changeset], because it's an internal change for a test library.
> Remove poison dependency

- .github/workflows/ci.yml
- config/config.exs
- test/appsignal_phoenix/event_handler_test.exs
- test/appsignal_phoenix/live_view_test.exs
- test/support/phoenix_web.ex
Test the latest Phoenix release candidate on CI to see what doesn't work.
The Phoenix instrumentation happens automatically and the `use Appsignal.Phoenix` line is no longer needed.
Replace deprecated namespace option with formats option to specify supported response formats, fixing warnings in Phoenix 1.8.
Change logger level from :warn to :warning to fix deprecation warning in newer Elixir versions.
Resolve all Phoenix.Logger and Phoenix.LiveView.Logger badmatch errors by:
Fixed router_dispatch telemetry events to include all expected fields: Added plug, plug_opts, route, path_params, pipe_through, log fields.
Fixed LiveView telemetry events to include all expected fields:
- Added missing uri field to mount events
- Added component and event fields to live_component …
> Add Phoenix 1.8 RC to the CI

- .github/workflows/ci.yml
It's been released, we don't need to test against the release candidate.
[skip review]
> Test against the final Phoenix 1.8 release
